sudo: "required"
language: "node_js"
node_js:
  - "stable"
services:
  - "docker"
before_install:
  - docker build -t meshfields/timeout-micro .
  - docker run -d -p 127.0.0.1:80:4567 meshfields/timeout-micro /bin/sh -c "cd /root/timeout-micro; npm start;"
  - docker ps -a
  - docker run meshfields/timeout-micro /bin/sh -c "cd /root/meshfields; npm test"
script:
  - npm test
deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch: master
